# Generated by Django 3.2 on 2021-04-16 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210417_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='a992ada997', max_length=25),
        ),
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(null=True, to='product.OrderProduct'),
        ),
    ]
