# Generated by Django 3.2 on 2021-04-16 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20210417_0333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='1cd6ac5b6e', max_length=25),
        ),
    ]
